//default action
export const FETCH_PRODUCTS_BEGIN = 'FETCH_PRODUCTS_BEGIN';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const FETCH_SINGLE_PRODUCT = 'FETCH_SINGLE_PRODUCT';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';
export const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY';
export const DECREMENT_QUANTITY = 'DECREMENT_QUANTITY';
export const ADD_TO_COMPARE = 'ADD_TO_COMPARE';
export const REMOVE_FROM_COMPARE_LIST = 'REMOVE_FROM_COMPARE_LIST';

// Auth
export const REGISTER_REQUEST   = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS   = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE   = 'REGISTER_FAILURE';

export const VERIFY_REQUEST     = 'VERIFY_REQUEST';
export const VERIFY_SUCCESS     = 'VERIFY_SUCCESS';
export const VERIFY_FAILURE     = 'VERIFY_FAILURE';

export const LOGIN_REQUEST      = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS      = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE      = 'LOGIN_FAILURE';

export const GOOGLE_REQUEST     = 'GOOGLE_REQUEST';
export const GOOGLE_SUCCESS     = 'GOOGLE_SUCCESS';
export const GOOGLE_FAILURE     = 'GOOGLE_FAILURE';

export const LOGOUT             = 'LOGOUT';

export const FORGOT_REQUEST     = 'FORGOT_REQUEST';
export const FORGOT_SUCCESS     = 'FORGOT_SUCCESS';
export const FORGOT_FAILURE     = 'FORGOT_FAILURE';

export const RESET_REQUEST      = 'RESET_REQUEST';
export const RESET_SUCCESS      = 'RESET_SUCCESS';
export const RESET_FAILURE      = 'RESET_FAILURE';

export const GET_USER_PROFILE_REQUEST = 'GET_USER_PROFILE_REQUEST';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAILURE = 'GET_USER_PROFILE_FAILURE';

export const UPDATE_USER_PROFILE_REQUEST = 'UPDATE_USER_PROFILE_REQUEST';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_FAILURE = 'UPDATE_USER_PROFILE_FAILURE';
